name: Publish API image
on:
    push:
        branches:
            - master
            - v3
        paths:
            - api/**
    workflow_dispatch:
jobs:
    push_to_registry:
        runs-on: ubuntu-latest
        name: Build and Push Docker image to Github Packages
        steps:
            - name: Check out repo
              uses: actions/checkout@v2
            - name: Login to GitHub registry
              uses: docker/login-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
            - name: Login to ghcr.io
              uses: docker/login-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push API
              uses: docker/build-push-action@v3
              with:
                  context: api
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/piston
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
